import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "UoB Book",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
        
        <footer className="flex justify-center mb-4  text-white"> © Proline Taxi</footer>
      </body>
    </html>
  );
}
