import type { Metadata } from "next";
import { Aleo, Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Suspense } from 'react';
import LayoutWrapper from "./conditinalnavbar";

const aleo = Aleo({ subsets: ["latin"], variable: "--font-aleo" });
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "UoB Taxi & Chauffeur",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${aleo.variable} ${inter.variable}`}>
        <SessionProvider>
          <LayoutWrapper>
            <main><Suspense fallback={<div>Loading...</div>}>{children}</Suspense></main>
          </LayoutWrapper>
        </SessionProvider>
      </body>
    </html>
  );
}
